export enum AppErrors {
  // Auth errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_INACTIVE = "USER_INACTIVE",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  ROLE_ALREADY_ASSIGNED = "ROLE_ALREADY_ASSIGNED",

  // Tenant errors
  TENANT_NOT_FOUND = "TENANT_NOT_FOUND",
  TENANT_INACTIVE = "TENANT_INACTIVE",
  TENANT_SLUG_TAKEN = "TENANT_SLUG_TAKEN",
  FEATURE_FLAG_NOT_FOUND = "FEATURE_FLAG_NOT_FOUND",
  MAX_USERS_REACHED = "MAX_USERS_REACHED",
  MAX_WORKFLOWS_REACHED = "MAX_WORKFLOWS_REACHED",

  // Workflow Definition errors
  WORKFLOW_DEFINITION_NOT_FOUND = "WORKFLOW_DEFINITION_NOT_FOUND",
  WORKFLOW_DEFINITION_NOT_DRAFT = "WORKFLOW_DEFINITION_NOT_DRAFT",
  WORKFLOW_DEFINITION_NOT_PUBLISHED = "WORKFLOW_DEFINITION_NOT_PUBLISHED",
  WORKFLOW_DEFINITION_ALREADY_PUBLISHED = "WORKFLOW_DEFINITION_ALREADY_PUBLISHED",
  WORKFLOW_STATE_NOT_FOUND = "WORKFLOW_STATE_NOT_FOUND",
  WORKFLOW_TRANSITION_NOT_FOUND = "WORKFLOW_TRANSITION_NOT_FOUND",
  WORKFLOW_INITIAL_STATE_REQUIRED = "WORKFLOW_INITIAL_STATE_REQUIRED",
  WORKFLOW_MULTIPLE_INITIAL_STATES = "WORKFLOW_MULTIPLE_INITIAL_STATES",
  TRANSITION_RULE_NOT_FOUND = "TRANSITION_RULE_NOT_FOUND",

  // Workflow Execution errors
  WORKFLOW_INSTANCE_NOT_FOUND = "WORKFLOW_INSTANCE_NOT_FOUND",
  WORKFLOW_INSTANCE_NOT_ACTIVE = "WORKFLOW_INSTANCE_NOT_ACTIVE",
  TRANSITION_NOT_ALLOWED = "TRANSITION_NOT_ALLOWED",
  TRANSITION_ROLE_FORBIDDEN = "TRANSITION_ROLE_FORBIDDEN",
  TRANSITION_RULES_FAILED = "TRANSITION_RULES_FAILED",
  TRANSITION_CONFLICT = "TRANSITION_CONFLICT",
  COMMENT_REQUIRED = "COMMENT_REQUIRED",
  IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED",
  DEFINITION_VERSION_NOT_FOUND = "DEFINITION_VERSION_NOT_FOUND",

  // Audit errors
  AUDIT_LOG_NOT_FOUND = "AUDIT_LOG_NOT_FOUND",

  // Notification errors
  NOTIFICATION_TEMPLATE_NOT_FOUND = "NOTIFICATION_TEMPLATE_NOT_FOUND",
  WEBHOOK_CONFIG_NOT_FOUND = "WEBHOOK_CONFIG_NOT_FOUND",
  NOTIFICATION_SEND_FAILED = "NOTIFICATION_SEND_FAILED",
  WEBHOOK_DELIVERY_FAILED = "WEBHOOK_DELIVERY_FAILED",

  // Rule Engine errors
  RULE_EVALUATION_ERROR = "RULE_EVALUATION_ERROR",
  RULE_TEMPLATE_NOT_FOUND = "RULE_TEMPLATE_NOT_FOUND",

  // Generic errors
  FORBIDDEN = "FORBIDDEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  TENANT_MISMATCH = "TENANT_MISMATCH",
}

